import { Link } from 'react-router-dom';
import { ArrowLeft, Calendar, Clock } from 'lucide-react';
import { MarketingLayout, Prose } from '@/components/marketing/MarketingLayout';
import { Seo } from '@/components/Seo';
import type { BlogPost } from '@/lib/blog';

// Shared chrome for individual blog posts — title block, byline, "back
// to blog" link, Article JSON-LD. Each post supplies its body as
// children. We don't render via MDX because every post is small and
// having them as TSX keeps the styling consistent without a build-time
// plugin chain.

export function BlogPostLayout({
  post,
  children,
}: {
  post: BlogPost;
  children: React.ReactNode;
}) {
  return (
    <MarketingLayout>
      <Seo
        title={post.title}
        description={post.excerpt}
        path={`/blog/${post.slug}`}
        ogType="article"
        // Per-post OG image generated by scripts/gen-og-images.mjs. Drops
        // into public/og/<slug>.png at build time. Re-run `npm run gen:og`
        // when titles change.
        ogImage={`https://affixai.com/og/${post.slug}.png`}
        jsonLd={{
          '@context': 'https://schema.org',
          '@type': 'BlogPosting',
          headline: post.title,
          description: post.excerpt,
          datePublished: post.iso_date,
          dateModified: post.iso_date,
          author: {
            '@type': 'Organization',
            name: post.author,
            url: 'https://affixai.com/about',
          },
          publisher: {
            '@type': 'Organization',
            name: 'AffixAI',
            logo: { '@type': 'ImageObject', url: 'https://affixai.com/logo.png' },
          },
          mainEntityOfPage: {
            '@type': 'WebPage',
            '@id': `https://affixai.com/blog/${post.slug}`,
          },
        }}
      />

      <article className="relative">
        <header className="max-w-3xl mx-auto px-6 pt-12 pb-6">
          <Link
            to="/blog"
            className="inline-flex items-center gap-1.5 text-xs text-fg-muted hover:text-fg transition mb-6"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to all posts
          </Link>
          <div className="flex items-center gap-3 text-xs text-fg-subtle mb-3">
            <span className="text-brand-300 font-medium">{post.tag}</span>
            <span>·</span>
            <span className="inline-flex items-center gap-1">
              <Calendar className="h-3 w-3" />
              {post.date}
            </span>
            <span>·</span>
            <span className="inline-flex items-center gap-1">
              <Clock className="h-3 w-3" />
              {post.read}
            </span>
          </div>
          <h1 className="font-display text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight leading-[1.1]">
            {post.title}
          </h1>
          <p className="mt-5 text-lg text-fg-muted leading-relaxed">
            {post.excerpt}
          </p>
        </header>

        <Prose>{children}</Prose>

        <footer className="max-w-3xl mx-auto px-6 pb-20 pt-6 text-sm text-fg-subtle">
          <hr className="border-border my-8" />
          <p>
            <strong className="text-fg">{post.author}</strong> · Published {post.date}
          </p>
          <p className="mt-2">
            Have feedback?{' '}
            <Link
              to="/contact"
              className="text-brand-300 hover:text-brand-200 underline underline-offset-2"
            >
              Get in touch
            </Link>{' '}
            — we read every reply.
          </p>
        </footer>
      </article>
    </MarketingLayout>
  );
}
